import Link from "next/link";
import { Check, GraduationCap, Info, Lock, Share2, Sparkles } from "lucide-react";

import { PageHeader, PageShell, Section, SectionEyebrow } from "@/components/page-shell";
import { Button } from "@/components/ui/button";

export const metadata = {
  title: "Membership — JobClubb",
  description:
    "Unlock the full job board, one-click apply, guaranteed interviews and upskilling.",
};

const MEMBER_BENEFITS = [
  "Unlock all live jobs",
  "Unlimited one-click apply",
  "Guaranteed employer interviews",
  "Full upskilling & certification access",
  "AI-generated, ATS-approved resume",
  "Location match — jobs near your home",
  "Priority support till you're hired",
];

/** SOP §3.3 — free tier sees these four fields only */
const FREE_FIELDS = [
  "Job location",
  "Job position",
  "Experience required",
  "Salary range",
];

export default function MembershipPage() {
  return (
    <PageShell>
      <PageHeader
        eyebrow="Why JobClubb membership"
        title="Your days of job searching are over"
        description="Free to join and browse. Membership unlocks the full board, one-click apply, guaranteed interviews and upskilling."
      />

      {/* Plans */}
      <Section>
        <div className="grid items-stretch gap-6 lg:grid-cols-3">
          {/* Free */}
          <PlanCard
            name="Free profile"
            price="₹0"
            cadence="always available"
            cta="Create free profile"
            href="/sign-up"
            variant="muted"
          >
            <p className="text-sm text-muted-foreground">Browse and see:</p>
            <ul className="mt-3 space-y-2.5">
              {FREE_FIELDS.map((f) => (
                <Feature key={f}>{f}</Feature>
              ))}
            </ul>
            <p className="mt-4 text-xs leading-5 text-muted-foreground">
              Full job details, applying and employer contact require an active
              membership.
            </p>
          </PlanCard>

          {/* Standard */}
          <PlanCard
            name="JobClubb Membership"
            price="₹1,499"
            cadence="/ year"
            badge="Most popular"
            cta="Join JobClubb now"
            href="/sign-up?plan=standard"
            variant="brand"
          >
            <ul className="space-y-2.5">
              {MEMBER_BENEFITS.map((b) => (
                <Feature key={b}>{b}</Feature>
              ))}
            </ul>
            <p className="mt-4 text-xs leading-5 text-muted-foreground">
              Paid securely via Razorpay. Renewal reminder 15 days before expiry.
            </p>
          </PlanCard>

          {/* Student */}
          <PlanCard
            name="Student Membership"
            price="₹1,199"
            cadence="incl. GST"
            icon={GraduationCap}
            cta="Redeem student code"
            href="/sign-up?plan=student"
            variant="muted"
          >
            <ul className="space-y-2.5">
              <Feature>All membership benefits</Feature>
              <Feature>Requires an admin-issued code</Feature>
              <Feature>Code valid for 48 hours</Feature>
              <Feature>Student ID upload for eligibility</Feature>
            </ul>
            <p className="mt-4 text-xs leading-5 text-muted-foreground">
              Codes are generated by the JobClubb admin team. Ask your institution or
              your nearest franchise partner.
            </p>
          </PlanCard>
        </div>

        {/* Referral */}
        <div className="mt-6 rounded-3xl border border-border bg-card p-8">
          <div className="flex flex-wrap items-start gap-5">
            <span className="flex size-12 flex-none items-center justify-center rounded-2xl bg-brand-accent/15 text-good">
              <Share2 className="size-5" />
            </span>
            <div className="min-w-0 flex-1">
              <SectionEyebrow>Refer &amp; earn</SectionEyebrow>
              <h2 className="mt-1.5 font-head text-xl font-bold tracking-tight">
                Every paying member gets a unique referral code
              </h2>
              <p className="mt-2 max-w-2xl leading-7 text-muted-foreground">
                Share your code and the first 5 people who join with it receive free
                membership. Those 5 free members don&apos;t receive their own shareable
                code — the referral chain stops there.
              </p>
              <div className="mt-4 flex flex-wrap items-center gap-3">
                <code className="rounded-lg border border-dashed border-brand/40 bg-muted px-4 py-2 font-mono text-sm font-semibold text-brand">
                  JC-JOIN-XXXX
                </code>
                <span className="text-sm text-muted-foreground">
                  0 of 5 redemptions used
                </span>
              </div>
            </div>
          </div>
        </div>
      </Section>

      {/* Why upskilling — PDF Tab 2 asks for this */}
      <Section className="bg-card">
        <SectionEyebrow>Why upskilling</SectionEyebrow>
        <h2 className="mt-2 font-head text-3xl font-extrabold tracking-tight">
          Getting shortlisted is a skill of its own
        </h2>
        <p className="mt-4 max-w-2xl leading-7 text-muted-foreground">
          Airlines, hotels and travel employers hire on grooming, communication and
          service instinct — not just qualifications. Upskilling is included with every
          membership so you walk into the interview prepared.
        </p>

        <div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
          {[
            {
              title: "Interview coaching",
              body: "Mock rounds modelled on real airline and hotel selection formats, including group discussions.",
            },
            {
              title: "Grooming & presentation",
              body: "The appearance and etiquette standards that cabin crew and front-office panels actually assess.",
            },
            {
              title: "Communication",
              body: "Spoken English and guest-handling practice pitched at service-industry expectations.",
            },
            {
              title: "Certification",
              body: "Sector certifications that make your profile stand out to hiring managers.",
            },
          ].map((item) => (
            <div key={item.title} className="rounded-2xl border border-border bg-background p-6">
              <Sparkles className="size-5 text-brand-accent" />
              <h3 className="mt-3 font-head font-bold tracking-tight">{item.title}</h3>
              <p className="mt-2 text-sm leading-6 text-muted-foreground">{item.body}</p>
            </div>
          ))}
        </div>
      </Section>

      {/* What's gated */}
      <Section>
        <div className="grid gap-6 lg:grid-cols-2">
          <div className="rounded-3xl border border-border bg-card p-8">
            <Lock className="size-5 text-brand" />
            <h2 className="mt-3 font-head text-xl font-bold tracking-tight">
              What members unlock
            </h2>
            <ul className="mt-4 space-y-2.5">
              {MEMBER_BENEFITS.map((b) => (
                <Feature key={b}>{b}</Feature>
              ))}
            </ul>
          </div>

          <div className="rounded-3xl border border-border bg-card p-8">
            <Info className="size-5 text-brand" />
            <h2 className="mt-3 font-head text-xl font-bold tracking-tight">
              How renewal works
            </h2>
            <ul className="mt-4 space-y-4 text-sm leading-6 text-muted-foreground">
              <li>
                <span className="font-head font-bold text-foreground">15 days before expiry</span>{" "}
                — we send a renewal reminder by email, SMS and in-app notification, with
                an option to update your resume in the same flow.
              </li>
              <li>
                <span className="font-head font-bold text-foreground">Closer to expiry</span>{" "}
                — a second reminder goes out so nothing lapses by accident.
              </li>
              <li>
                <span className="font-head font-bold text-foreground">Your free profile</span>{" "}
                stays available either way. Cancel anytime.
              </li>
            </ul>
          </div>
        </div>

        <div className="mt-8 text-center">
          <Button
            className="bg-brand font-head text-brand-foreground hover:bg-brand-dark"
            nativeButton={false}
            render={<Link href="/sign-up" />}
          >
            Become a Member
          </Button>
        </div>
      </Section>
    </PageShell>
  );
}

function PlanCard({
  name,
  price,
  cadence,
  badge,
  icon: Icon,
  cta,
  href,
  variant,
  children,
}: {
  name: string;
  price: string;
  cadence: string;
  badge?: string;
  icon?: React.ComponentType<{ className?: string }>;
  cta: string;
  href: string;
  variant: "brand" | "muted";
  children: React.ReactNode;
}) {
  return (
    <div
      className={`relative flex h-full flex-col rounded-3xl border p-8 ${
        variant === "brand"
          ? "border-brand bg-card shadow-lg"
          : "border-border bg-card"
      }`}
    >
      {badge && (
        <span className="absolute -top-3 left-8 rounded-full bg-brand px-3 py-1 font-head text-xs font-bold text-brand-foreground">
          {badge}
        </span>
      )}
      {Icon && <Icon className="mb-3 size-5 text-brand" />}
      <h3 className="font-head text-lg font-bold tracking-tight">{name}</h3>
      <p className="mt-3 flex flex-wrap items-baseline gap-2">
        <span className="font-head text-4xl font-extrabold tracking-tight text-brand">
          {price}
        </span>
        <span className="text-sm text-muted-foreground">{cadence}</span>
      </p>
      <div className="mt-6 flex-1">{children}</div>
      <Button
        className={`mt-7 w-full shrink-0 font-head ${
          variant === "brand"
            ? "bg-brand text-brand-foreground hover:bg-brand-dark"
            : ""
        }`}
        variant={variant === "brand" ? "default" : "outline"}
        nativeButton={false}
        render={<Link href={href} />}
      >
        {cta}
      </Button>
    </div>
  );
}

function Feature({ children }: { children: React.ReactNode }) {
  return (
    <li className="flex items-start gap-2.5 text-sm">
      <Check className="mt-0.5 size-4 flex-none text-good" />
      <span className="text-muted-foreground">{children}</span>
    </li>
  );
}
